services:
  webui:
    stdin_open: true
    tty: true
    privileged: true
    build:
      dockerfile: 'Dockerfile'
      args:
        STABLE_DIFFUSION_VERSION: ${STABLE_DIFFUSION_VERSION}
    env_file:
      - .env.example
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - ${PORT}:7860
      - 8189:8189
    volumes:
      - venv:/app/venv
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./extensions:/app/extensions
      - ./extensions-builtin:/app/extensions-builtin
      - ./repositories:/app/repositories
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider http://localhost:7860 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 400
      start_period: 5s
      start_interval: 2s

volumes:
  venv:
