services:
  webui:
    stdin_open: true
    tty: true
    privileged: true
    build:
      dockerfile: 'Dockerfile'
      args:
        STABLE_DIFFUSION_VERSION: ${STABLE_DIFFUSION_VERSION}
    environment:
      - STABLE_DIFFUSION_REPO=https://github.com/joypaul162/Stability-AI-stablediffusion.git
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - ${PORT}:7860
    volumes:
      - venv:/app/venv
      - ./models:/app/stable-diffusion-webui/models
      - ./outputs:/app/stable-diffusion-webui/outputs
      - ./extensions:/app/stable-diffusion-webui/extensions
      - ./extensions-builtin:/app/stable-diffusion-webui/extensions-builtin
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider http://localhost:7860 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 400
      start_period: 5s
      start_interval: 2s

volumes:
  venv:
